version: "3"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
